### ISSUE TITLE
Publish plugin marker artifact to Sonatype

### ISSUE THREAD

**Issue by technoir42** [runningcode/fladle#104] opened 2020-05-11 18:55 UTC
Version 0.9.2-SNAPSHOT cannot be applied using plugins DSL because marker artifact is missing from Sonatype.

```gradle
// settings.gradle:
pluginManagement {
    repositories {
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
            mavenContent {
                snapshotsOnly()
            }
        }
        gradlePluginPortal()
    }
    plugins {
        id "com.osacky.fladle" version "0.9.2-SNAPSHOT"
    }
}

// build.gradle:
plugins {
    id "com.osacky.fladle" 
}
```

```
Plugin [id: 'com.osacky.fladle', version: '0.9.2-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.osacky.fladle:com.osacky.fladle.gradle.plugin:0.9.2-SNAPSHOT')
  Searched in the following repositories:
    maven(https://oss.sonatype.org/content/repositories/snapshots/)
    Gradle Central Plugin Repository
```

**Comment by runningcode** [comment] 2020-05-11 19:29
Thanks for filing the issue with the error and your buildscript.

It looks like you are specifying the wrong artifact. it should be asking for `com.osacky.flank.gradle:fladle:0.9.2-SNAPSHOT`
I'm not sure what the correct syntax using `pluginMangement` would be. But using the old syntax it would look like this:
```
buildscript {
  repositories {
    maven {
      url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
  }
  dependencies {
    classpath "com.osacky.flank.gradle:fladle:0.9.2"
  }
}

apply plugin: "com.osacky.fladle"
```

**Comment by technoir42** [comment] 2020-05-11 19:52
I copy-pasted the example for plugins DSL from https://plugins.gradle.org/plugin/com.osacky.fladle and just changed the version to 0.9.2-SNAPSHOT.

**Comment by technoir42** [comment] 2020-05-11 19:59
`com.osacky.fladle:com.osacky.fladle.gradle.plugin:0.9.2-SNAPSHOT` is coordinates of the marker artifact which typically gets published to Gradle plugin portal, but it can also be published to any other repository like Sonatype so plugins DSL would also work.

**Comment by runningcode** [comment] 2020-05-11 20:15
I can confirm that the buildscript syntax I specified in the comment above works. The plugin is publishing the market correctly as `com.osacky.flank.gradle:fladle:0.9.2-SNAPSHOT`.
I'm going to try to find the correct syntax to use for the `pluginManagement`.

**Comment by runningcode** [comment] 2020-05-11 20:20
Oh, I see what you mean with the market artifact: https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers

**Comment by runningcode** [comment] 2020-05-11 20:33
The following syntax will work:
`settings.gradle`
```
pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.namespace == "com.osacky") {
                useModule("com.osacky.flank.gradle:fladle:${requested.version}")
            }
        }
    }
    repositories {
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
        }
        gradlePluginPortal()
    }
}
```
`build.gradle.kts`
```
plugins {
  id("com.osacky.fladle") version "0.9.2-SNAPSHOT"
}
```

**Comment by runningcode** [comment] 2020-05-11 21:16
Waiting on permission to publish the marker artifact: https://issues.sonatype.org/browse/OSSRH-57528
Thanks for filing this!

**Comment by runningcode** [comment] 2020-05-11 21:29
Snapshot marker has been published! I'll update the release instructions to ensure that this is always published.

**Comment by runningcode** [comment] 2020-05-11 22:38
Added this to the docs as well: https://runningcode.github.io/fladle/snapshots/

Thanks again for filing this. Closing it out.

**Closed by runningcode** 2020-05-11 22:38 UTC
